name: Quick build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  assemble_and_test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Assemble
        run: ./gradlew assemble
      - name: JVM tests
        run: ./gradlew jvmTest
      - name: iOS tests
        run: ./gradlew iosX64Test
